stages:
  - pharaon-prod
deploy_pharaon:
  stage: pharaon-prod
  only:
    - dev
  when:
    - manual
  tags:
    - pharaon-prod
  script:
    - docker compose -p $CI_PROJECT_NAME-$CI_COMMIT_BRANCH-test up -d --build
    - docker image prune -f